# Generated by Django 4.2.7 on 2023-11-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0002_remove_imagevehicule_vehicule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nombredeplacevehicule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nombredeplacevehicule',
            name='nom',
        ),
        migrations.AddField(
            model_name='nombredeplacevehicule',
            name='nombre',
            field=models.IntegerField(null=True),
        ),
    ]
