# Generated by Django 4.2.7 on 2023-11-14 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0003_remove_nombredeplacevehicule_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='en_vente',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_list', to=settings.AUTH_USER_MODEL)),
                ('vehicles', models.ManyToManyField(related_name='favorited_by', to='appapi.vehicule')),
            ],
        ),
    ]
