# Generated by Django 4.2.7 on 2023-11-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0004_vehicule_en_vente_favoritelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='en_location',
            field=models.BooleanField(default=False),
        ),
    ]
