# Generated by Django 4.2.7 on 2023-11-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0006_publicite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='medias/photos_clients/'),
        ),
        migrations.AlterField(
            model_name='imagevehicule',
            name='image',
            field=models.ImageField(null=True, upload_to='medias/images_vehicule/'),
        ),
    ]
